---
title: "Salud y M. Ambiente"
author: ["{{< var dberroeta.name >}}"]
---

## Resumen

La dimensión de salud y medio ambiente del {{< var coi.ssname >}} busca capturar cómo las condiciones físicas, ecológicas y de infraestructura urbana inciden en la salud y el bienestar infantil. Considera factores de exposición (como contaminación atmosférica o calor extremo) y factores protectores (como acceso a espacios verdes o servicios de salud). Esta dimensión reconoce que el entorno natural y construido constituye un determinante estructural del desarrollo físico, cognitivo y emocional durante la infancia.


<!-- ## Definición -->

<!-- Esta dimensión caracteriza la calidad del ambiente físico y sanitario del vecindario, evaluando tanto riesgos (contaminación, calor, residuos peligrosos) como oportunidades (acceso a áreas verdes, servicios de salud y entornos caminables). Afecta la salud desde etapas tempranas de la vida, incluyendo efectos prenatales, y puede amplificar desigualdades sociales preexistentes. -->


## Objetivos

*	Medir los niveles de exposición territorial a factores ambientales de riesgo (contaminación del aire, calor extremo, residuos).
*	Estimar la presencia de recursos que promuevan entornos seguros y saludables para niños y sus familias.
*	Identificar desigualdades espaciales en condiciones ambientales críticas para el desarrollo infantil.


## Dominio y sus indicadores

::: {}
| Dominio            | Indicador                           |
|--------------------------|:----------------------------------:|
| {{< var icalor.dominio >}}      | {{< var icalor.name >}} <br>  | 
| {{< var particulas.dominio >}} |{{< var particulas.name >}}<br>  {{< var ozono.name >}} <br>  {{< var industriales.name >}} <br>  {{< var residuos.name >}} |


: Dimensión de Salud y Medio Ambiente {#tbl-saludMA  tbl-colwidths="[40, 50]"}
:::


## Consideraciones metodológicas

La mayoría de los indicadores provienen de fuentes georreferenciadas de variada resolución espacial, incluyendo sensores remotos (PM2.5, temperatura), modelos ambientales (ozono, riesgo tóxico), y bases de datos públicas y censales. Los indicadores se estandarizan y normalizan para representar oportunidades (valores más altos) o riesgos (valores invertidos).


## Consideraciones conceptuales

*	**Causalidad acumulativa**: Las exposiciones ambientales adversas tienden a acumularse en comunidades vulnerables, amplificando impactos en salud infantil.

*	**Equidad ambiental**: La distribución desigual de entornos saludables refleja patrones históricos de planificación urbana, marginación territorial y desinversión.

* **Interdependencia**: La salud infantil se ve influida por la combinación de factores ecológicos, sanitarios y comunitarios.


## Adaptación al contexto nacional (Chile)

En el caso chileno, los indicadores de esta dimensión fueron construidos utilizando una combinación de:

**Productos satelitales de libre acceso**

*	Material particulado fino (PM2.5) mediante modelos de regresión geoestadística y validación cruzada.
* Temperaturas extremas y olas de calor.
<!-- * Índices de vegetación (NDVI, EVI) como proxy de acceso a entornos naturales. -->

**Datos abiertos del Ministerio del Medio Ambiente ({{< var mma.sigla >}}) y sus instituciones**

* Niveles de ozono troposférico y estaciones de monitoreo de calidad del aire.
* Localización de sitios contaminados (Sistema {{< var retc.sigla >}}).
<!-- * Capas de ruido ambiental y uso de suelo urbano. -->


